name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      docker:

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push client image
        run: |
          docker build -t migzxc23/multi-client -f./client/Dockerfile.dev./client
          docker push migzxc23/multi-client

      - name: Build and push nginx image
        run: |
          docker build -t migzxc23/multi-nginx./nginx
          docker push migzxc23/multi-nginx

      - name: Build and push server image
        run: |
          docker build -t migzxc23/multi-server./server
          docker push migzxc23/multi-server

      - name: Build and push worker image
        run: |
          docker build -t migzxc23/multi-worker./worker
          docker push migzxc23/multi-worker

      - name: Deploy to Elastic Beanstalk
        uses: aws-actions/beanstalk-deploy@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          region: ap-southeast-2
          application-name: multi-docker
          environment-name: Multi-docker-env
          bucket-name: elasticbeanstalk-ap-southeast-2-767397956932
          bucket-path: docker-multi
          zip-file:.