name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and test Docker image
      run: |
        docker build -t migzxc23/react-test -f ./client/Dockerfile.dev ./client
        docker run -e CI=true migzxc23/react-test npm test
    
    - name: Build Docker images
      run: |
        docker build -t migzxc23/multi-client ./client
        docker build -t migzxc23/multi-nginx ./nginx
        docker build -t migzxc23/multi-server ./server
        docker build -t migzxc23/multi-worker ./worker
    
    - name: Push Docker images
      run: |
        docker push migzxc23/multi-client
        docker push migzxc23/multi-nginx
        docker push migzxc23/multi-server
        docker push migzxc23/multi-worker
